const A={
button:'assets/figma/reaction-button.png',liquid:'assets/figma/reaction-liquid.png',body:'assets/figma/reaction-body.png',
this:'assets/figma/this.png',glp:'assets/figma/glp.png',chicken:'assets/figma/chicken.png',cola:'assets/figma/cola.png',egg:'assets/figma/egg.png',water:'assets/figma/water.png',finish:'assets/figma/finish.png',donut:'assets/figma/donut.png',salad:'assets/figma/salad.png',tteok:'assets/figma/tteok.png',dumb:'assets/figma/dumbbell.png',shoe:'assets/figma/shoe.png',
f1:'assets/figma/fixed1.png',f2:'assets/figma/fixed2.png',f3:'assets/figma/fixed3.png',f4:'assets/figma/fixed4.png',f5:'assets/figma/fixed5.png',
blow:'assets/figma/blister-lower.png',stdthis:'assets/figma/output-this.png',s4:'assets/figma/out-fixed2.png',s2:'assets/figma/out-fixed5.png',s5:'assets/figma/out-fixed1.png',s3:'assets/figma/out-fixed3.png',s6:'assets/figma/out-fixed4.png',btop:'assets/figma/blister-upper.png',retry:'assets/figma/retry.png'
};
const VAR={w1:'assets/figma/w1.png',w2:'assets/figma/w2.png',w3:'assets/figma/w3.png',w4:'assets/figma/w4.png',w5:'assets/figma/w5.png',w6:'assets/figma/w6.png',w7:'assets/figma/w7.png',w8:'assets/figma/w8.png',w9:'assets/figma/w9.png',w10:'assets/figma/w10.png',m1:'assets/figma/m1.png',m2:'assets/figma/m2.png',m3:'assets/figma/m3.png',m4:'assets/figma/m4.png',m5:'assets/figma/m5.png',m6:'assets/figma/m6.png'};
const app=document.querySelector('#app'),S=document.createElement('div');S.className='stage';app.appendChild(S);let SCALE=1;function scale(){SCALE=Math.min(innerWidth/1920,innerHeight/1080);S.style.transform=`scale(${SCALE})`;S.style.left='0px';S.style.top='0px'}addEventListener('resize',scale);scale();
const H=n=>`<div class="header"><span class="brand">PRESCRIBED:</span><span class="sub">JUST ONE MORE OPTION</span><span class="step">${n}</span></div>`;const I=(u,c='',s='')=>`<img draggable="false" src="${u}" class="${c}" style="${s}">`;function show(x){[...document.querySelectorAll('.screen')].forEach(e=>e.classList.add('hidden'));x.classList.remove('hidden')}
const R=document.createElement('section');R.className='screen reaction';R.innerHTML=H('01')+`<video class="video" preload="auto" playsinline webkit-playsinline></video><canvas class="video-poster"></canvas><div class="hero"><span class="orange">GLP-1</span>
MAKES
YOU
<span class="white">FIT.</span></div><div class="injector" id="injector"><div class="injwrap full button"><div class="injrot">${I(A.button)}</div></div><div class="injwrap clicked"><div class="injrot">${I(A.button)}</div></div><div class="injwrap full liquid"><div class="injrot">${I(A.liquid)}</div></div><div class="injwrap end"><div class="injrot"><div class="crop">${I(A.liquid)}</div></div></div><div class="injwrap full body"><div class="injrot">${I(A.body)}</div></div></div><div class="cover"></div>`;S.appendChild(R);
const V=R.querySelector('video'),posterCanvas=R.querySelector('.video-poster'),inj=R.querySelector('#injector'),baseBtn=inj.querySelector('.button'),endBtn=inj.querySelector('.clicked'),baseLiq=inj.querySelector('.liquid'),endLiq=inj.querySelector('.end');
function drawVideoPoster(){if(!V.videoWidth||!V.videoHeight)return;posterCanvas.width=V.videoWidth;posterCanvas.height=V.videoHeight;const ctx=posterCanvas.getContext('2d');ctx.clearRect(0,0,posterCanvas.width,posterCanvas.height);ctx.drawImage(V,0,0,posterCanvas.width,posterCanvas.height);posterCanvas.style.display='block';V.style.opacity='0'}
function resetVideoToFirstFrame(){return new Promise((resolve,reject)=>{V.pause();V.style.opacity='0';posterCanvas.style.display='none';const capture=()=>requestAnimationFrame(()=>requestAnimationFrame(()=>{drawVideoPoster();resolve()}));const seek=()=>{if(Math.abs(V.currentTime)<=0.01){try{V.currentTime=0}catch(e){}capture();return}let finished=false;const done=()=>{if(finished)return;finished=true;V.removeEventListener('seeked',done);capture()};V.addEventListener('seeked',done,{once:true});try{V.currentTime=0}catch(e){done()}setTimeout(()=>{if(!finished&&Math.abs(V.currentTime)<=0.05)done()},400)};if(V.readyState>=2)seek();else{V.addEventListener('loadeddata',seek,{once:true});V.addEventListener('error',()=>reject(V.error||new Error('video load failed')),{once:true})}})}
V.onplaying=()=>{posterCanvas.style.display='none';V.style.opacity='1'};
V.src='assets/reaction-video-web.mp4';V.load();const videoReady=resetVideoToFirstFrame();let p=0,raf,start;function resetInj(){p=0;baseBtn.style.opacity=1;endBtn.style.opacity=0;baseLiq.style.opacity=1;endLiq.style.opacity=0;inj.style.opacity='1';inj.style.pointerEvents='auto';inj.style.animation='pulse 1s ease-in-out infinite alternate';inj.style.filter=''}function tick(t){if(!start)start=t;p=Math.min(1,(t-start)/1300);baseBtn.style.opacity=1-p;endBtn.style.opacity=p;baseLiq.style.opacity=1-p;endLiq.style.opacity=p;if(p<1)raf=requestAnimationFrame(tick);else{inj.style.animation='none';inj.style.filter='none';inj.style.opacity='0';inj.style.pointerEvents='none';videoReady.then(()=>{try{V.currentTime=0}catch(e){};return V.play()}).catch(console.error)}}inj.onpointerdown=e=>{e.preventDefault();start=0;cancelAnimationFrame(raf);raf=requestAnimationFrame(tick)};addEventListener('pointerup',()=>{if(p<1){cancelAnimationFrame(raf);resetInj()}});V.onended=()=>show(IN);
const IN=document.createElement('section');IN.className='screen input hidden';IN.innerHTML=H('02')+I(A.this,'absimg thischar');S.appendChild(IN);const tc=IN.querySelector('.thischar');
const fixed=[[A.f5,95],[A.f4,317],[A.f1,539],[A.f2,1180],[A.f3,1402]];fixed.forEach(([u,x])=>IN.insertAdjacentHTML('beforeend',I(u,'absimg fixed',`left:${x}px;top:769px;width:182px;height:274px`)));
const state={weight:8,muscle:3,weightLossActions:0,usedRunning:false,usedStrength:false,visual:'weight',itemHistory:[]};const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function currentVisual(){return state.visual==='muscle'?(VAR['m'+state.muscle]||A.this):(VAR['w'+state.weight]||A.this)}function renderChar(){tc.src=currentVisual()}
function applyItem(k){state.itemHistory.push(k);if(k==='glp'){state.weight=clamp(state.weight-2,1,10);state.weightLossActions++;state.visual='weight'}else if(k==='salad'){state.weight=clamp(state.weight-1,1,10);state.weightLossActions++;state.visual='weight'}else if(['cola','donut','tteok'].includes(k)){state.weight=clamp(state.weight+1,1,10);state.visual='weight'}else if(k==='shoe'){state.weight=clamp(state.weight-1,1,10);state.weightLossActions++;state.usedRunning=true;state.muscle=(state.usedStrength||state.muscle===5)?6:4;state.visual='muscle'}else if(k==='dumb'){state.usedStrength=true;state.muscle=(state.usedRunning||state.muscle===4)?6:5;state.visual='muscle'}else if(k==='chicken'||k==='egg'){if(state.muscle<3){state.muscle++;state.visual='muscle'}}renderChar();tc.classList.remove('applied');void tc.offsetWidth;tc.classList.add('applied')}
const items=[['dumb',A.dumb,93,188,236,172,0],['tteok',A.tteok,472,102,235,172,0],['donut',A.donut,938,112,206,171,0],['chicken',A.chicken,1277,100,183,241,0],['salad',A.salad,1581,135,206,171,0],['water',A.water,83,387,183,241,0],['egg',A.egg,407,337,183,241,0],['glp',A.glp,1296.271,316,183,240,-28.977],['cola',A.cola,1703,316,168,220,0],['shoe',A.shoe,1494,469,209,217,0]];
const floats=[];items.forEach((a,i)=>{const e=document.createElement('div');e.className='item floatObject';e.dataset.k=a[0];Object.assign(e.style,{left:a[2]+'px',top:a[3]+'px',width:a[4]+'px',height:a[5]+'px','--base-rot':a[6]+'deg'});e.innerHTML=I(a[1],'itemImage',a[0]==='tteok'?'width:109.64%;left:-4.82%':'');IN.appendChild(e);const o={el:e,x:a[2],y:a[3],w:a[4],h:a[5],r:a[6],fx:0,fy:0,dx:0,dy:0,drag:false,phase:i*1.17,speed:.00080+(i%4)*.00005,ax:8+(i%3)*2,ay:6+(i%2)*2};floats.push(o);let sx=0,sy=0,sdx=0,sdy=0;e.onpointerdown=ev=>{ev.preventDefault();o.drag=true;sx=ev.clientX;sy=ev.clientY;sdx=o.dx;sdy=o.dy;e.classList.add('dragging');IN.classList.add('drag-active');e.setPointerCapture?.(ev.pointerId)};e.onpointermove=ev=>{if(!o.drag)return;o.dx=sdx+(ev.clientX-sx)/SCALE;o.dy=sdy+(ev.clientY-sy)/SCALE;const cx=o.x+o.fx+o.dx+o.w/2,cy=o.y+o.fy+o.dy+o.h/2;IN.classList.toggle('drag-over',cx>=695&&cx<=1206&&cy>=283&&cy<=1049)};const drop=ev=>{if(!o.drag)return;o.drag=false;e.classList.remove('dragging');const cx=o.x+o.fx+o.dx+o.w/2,cy=o.y+o.fy+o.dy+o.h/2;if(cx>=695&&cx<=1206&&cy>=283&&cy<=1049)applyItem(e.dataset.k);o.dx=o.dy=0;IN.classList.remove('drag-active','drag-over')};e.onpointerup=drop;e.onpointercancel=drop});function floatTick(t){floats.forEach(o=>{if(!o.drag){o.fx=Math.sin(t*o.speed+o.phase)*o.ax;o.fy=Math.sin(t*o.speed*.73+o.phase*1.31)*o.ay}o.el.style.transform=`translate(${o.fx+o.dx}px,${o.fy+o.dy}px) rotate(${o.r}deg)`});requestAnimationFrame(floatTick)}requestAnimationFrame(floatTick);
IN.insertAdjacentHTML('beforeend',`<button class="figma-button finish-button" aria-label="Finish"><span class="button-art">${I(A.finish)}</span><span class="button-label">FINISH</span></button>`);
const ST=document.createElement('section');ST.className='screen output standard hidden';ST.innerHTML=`<div class="fig-wrap blister" style="left:219.2px;top:-289.3px;width:2016.6px;height:1845.301px;z-index:0"><div style="width:1119.28px;height:1678.019px;transform:rotate(57.52deg)">${I(A.blow,'fillimg')}</div></div><div id="standardChars"></div><div class="fig-wrap blister" style="left:219.2px;top:-289.3px;width:2016.6px;height:1845.301px;z-index:7"><div style="width:1119.28px;height:1678.019px;transform:rotate(57.52deg);opacity:.8">${I(A.btop,'fillimg')}</div></div>${H('03')}<div class="resultword r1">IS THIS UR </div><div class="resultword r2">IDEAL?</div><button class="figma-button retry-button" aria-label="Retry"><span class="button-art">${I(A.retry)}</span><span class="button-label">RETRY</span></button>`;S.appendChild(ST);
const stdData=[[A.stdthis,932.93,294.16,true],[A.s4,1123.93,588.16,false],[A.s2,1374,16,false],[A.s5,1565,310,false],[A.s3,505,569,false],[A.s6,696,863,false]];function buildStandard(){const c=ST.querySelector('#standardChars');c.innerHTML='';stdData.forEach(a=>{const w=document.createElement('div');w.className='fig-wrap stdwrap';Object.assign(w.style,{left:a[1]+'px',top:a[2]+'px',width:'419.126px',height:'382.775px',zIndex:'2'});w.innerHTML=`<div style="width:232.565px;height:348.847px;transform:rotate(57.77deg)">${I(a[3]?currentVisual():a[0],'fillimg')}</div>`;c.appendChild(w)})}
const FR=document.createElement('section');FR.className='screen output free hidden';FR.innerHTML=`<div id="freeChars"></div>${H('03')}<div class="resultword r1">IS THIS UR </div><div class="resultword r2">IDEAL?</div><button class="figma-button retry-button" aria-label="Retry"><span class="button-art">${I(A.retry)}</span><span class="button-label">RETRY</span></button>`;S.appendChild(FR);const freeData=[[1564,159],[1213,518],[819,329],[446,593],[48,487],[1184,-113]];function buildFree(){const c=FR.querySelector('#freeChars');c.innerHTML='';freeData.forEach(a=>{const im=new Image();im.className='freechar';im.src=currentVisual();Object.assign(im.style,{left:a[0]+'px',top:a[1]+'px',width:'352px',height:'528px'});c.appendChild(im)})}
function finish(){const standard=state.weight<=4||state.weightLossActions>=2;if(standard){buildStandard();show(ST)}else{buildFree();show(FR)}}IN.querySelector('.finish-button').onclick=finish;[...document.querySelectorAll('.retry-button')].forEach(b=>b.onclick=()=>{Object.assign(state,{weight:8,muscle:3,weightLossActions:0,usedRunning:false,usedStrength:false,visual:'weight',itemHistory:[]});tc.src=A.this;cancelAnimationFrame(raf);start=0;resetInj();resetVideoToFirstFrame().then(()=>show(R)).catch(()=>show(R))});
resetInj();